// for compiling using new fpgui-develop branch
{.$DEFINE fpgui-develop} // uncomment for building with fpgui-develop

// for dynamic load of xlib and xft
{$DEFINE DYNLOAD} // uncomment for dynamic load of xlib and xft

// for compiling into library 
{.$DEFINE islibrary} // uncomment for building library (native and java)
{.$DEFINE java}   // uncomment for building java library

// for integration into ideU
{.$DEFINE ideu} // uncomment for building integration into ideU

